const questions = [
    {"question": "Fiziologik reflekslar qanday ikki guruhga bo‘linadi:", "answers": ["Shartli, shartsiz", "Bukuvchi", "Yozuvchi", "Teri"], "correct": 0},
    {"question": "Medullyar qonus shikastlanganda qaysi refleks yo‘qoladi:", "answers": ["Anal", "Tizza", "Axill", "Tovon"], "correct": 0},
    {"question": "Bemorda tovon barmoqlarini to‘satdan va qattiq passiv paralich tomonga bukilganda, oyoq tizza va tos-son bug‘imida ixtiyorsiz bukiladi. Bu simptom qanday nomlanadi:", "answers": ["Mari-fua-bexterev", "Bexterev", "Rossolimo", "Gordon"], "correct": 0},
    {"question": "Bitseps refleksiga orqa miyaning qaysi segmenti javob beradi:", "answers": ["S5-S6", "L2- L4", "D7-D8", "L5-S1"], "correct": 0},
    {"question": "Tritseps refleksiga orqa miyaning qaysi segmenti javob beradi:", "answers": ["S7-S8", "L5-S1", "D7-D8", "L2- L4"], "correct": 0},
    {"question": "Patellyar refleksiga orqa miyaning qaysi segmenti javob beradi:", "answers": ["L2- L4", "S5-S6", "S7-S8", "D7-D8"], "correct": 0},
    {"question": "Axill refleksiga orqa miyaning qaysi segmenti javob beradi:", "answers": ["L5-S1", "S5-S6", "S7-S8", "D7-D8"], "correct": 0},
    {"question": "Yuqori qorin refleksiga orqa miyaning qaysi segmenti javob beradi:", "answers": ["D7-D8", "S5-S6", "S7-S8", "L5-S1"], "correct": 0},
    {"question": "O‘rta qorin refleksiga orqa miyaning qaysi segmenti javob beradi:", "answers": ["D9-D10", "S7-S8", "S5-S6", "D7-D8"], "correct": 0},
    {"question": "Pastki qorin refleksiga orqa miyaning qaysi segmenti javob beradi:", "answers": ["D11-D12", "S5-S6", "D7-D8", "D9-D10"], "correct": 0},
    {"question": "Pay va periostal reflekslar qachon oshadi:", "answers": ["Markaziy paralichda", "Periferik paralichda", "Periferik va markaziy paralichda", "Orqa miya oldingi shoxi zararlanganda"], "correct": 0},
    {"question": "Yozuvchi patologik reflekslarga kirmaydi:", "answers": ["Rossolimo", "Oppengeym", "Babinskiy", "Sheffer"], "correct": 0},
    {"question": "Bukuvchi patologik reflekslarga kirmaydi:", "answers": ["Babinskogo", "Bexterev Mari Fua", "Bextereva Mendelya", "Jukovskiy"], "correct": 0},
    {"question": "Pay va periostal reflekslar qachon pasayadi yoki yo‘qoladi:", "answers": ["Periferik paralichda", "Markaziy paralichda", "Periferik va markaziy paralichda", "Orqa miya yen ustunchasi zararlanganda"], "correct": 0},
    {"question": "Qaysi sindromda oral avtomatizm refleksii xarakterli:", "answers": ["Soxtabulьbar", "Sharko sindromi", "Bulьbar", "Astenik"], "correct": 0},
    {"question": "Reflektor yoyi nechta qismdan iborat:", "answers": ["Afferent", "Efferent", "Afferent va Efferent", "Periferik"], "correct": 0},
    {"question": "Qo‘lda patologik piramida simptomi – refleksi:", "answers": ["Rossolimo", "Sheffer", "Oppengeym", "Babinskiy"], "correct": 0},
    {"question": "Nima zararlanganda patologik reflekslar xarakterli:", "answers": ["Markaziy harakat neyroni", "Periferik harakat neyroni", "Miyacha", "Talamus"], "correct": 0},
    {"question": "Medullyar qonus zararlanganda qaysi reflekslar pasayadi:", "answers": ["Anal", "Axill", "Tovon", "Kremaster"], "correct": 0},
    {"question": "Oyoqni tizza va dumgaza son bo‘gimida bukkanda birdaniga paralich tomonda passiv tovon barmoklarini bukilishi ko‘zatildi. Bu simptom qanday nomlanadi:", "answers": ["Mari-fua-bexterev", "Rossolimo", "Bexterev", "Gunn"], "correct": 0},
    {"question": "Medullyar qonus zararlanganda qaysi refleks yo‘qoladi", "answers": ["Anal", "Axill", "Tizza", "Kremaster"], "correct": 0},
    {"question": "Pay va periostal reflekslar qachon oshadi", "answers": ["Markaziy paralichda", "Periferik paralichda", "Periferik va markaziy paralichda", "Orqa miyaning oldingi shoxi zararlanganda"], "correct": 0},
    {"question": "Yozuvchi patologik reflekslarga kirmaydi", "answers": ["Rossolimo", "Sheffer", "Gordon", "Oppengeym"], "correct": 2},
    {"question": "Bukuvchi patologik reflekslarga kirmaydi", "answers": ["Babinskiy", "Bexterev-Mendel", "Jukovskiy", "Jukovskiy"], "correct": 2},
    {"question": "Pay va periostal reflekslar qachon pasayadi", "answers": ["Periferik paralichda", "Periferik va markaziy paralichda", "Orqa miyaning oldingi shoxi zararlanganda", "Markaziy paralichda"], "correct": 0}
];