const questions  = [
    {"question": "Bemorda ko‘rish o‘tkirligi saklangan, lekin ko‘rsatilgan predmetlarni tanimaydi. Patologiyani ko‘rsating", "answers": ["Anozognoziya", "Apraksiya", "Aleksiya", "Autotopognoziya"], "correct": 0},
    {"question": "Po‘stlokdagi praksis markazini ko‘rsating", "answers": ["40 soxa.", "44-45 Brodman soxasi", "39-42 soxalar", "22 Vernike soxasi"], "correct": 0},
    {"question": "Miya ustuninn nima xosil kiladi", "answers": ["Uzunchok miya, miya kuprigi, miya oyokchasi", "Orka miya, uzunchok miya", "Uzunchok miya, miyacha", "Uzunchok miya, miya kuprigi"], "correct": 0},
    {"question": "Jekson alьternirlashgan sindromida kaysi BMN zararlanadi?", "answers": ["XII", "III", "V", "VIII"], "correct": 0},
    {"question": "Kaysi alьternirlashgan sindromda III BMN zararlanadi?", "answers": ["Veber", "Miyar-Gubler", "Fovilь", "Vallenberg-Zaxarchenko"], "correct": 0},
    {"question": "Kaysi alьternirlashgan sindromda yuz nervining periferik falajlashi kuzatiladi?", "answers": ["Miyyar-Gubler", "Veber", "Fovilь", "Vallenberg-Zaxarchenko"], "correct": 0},
    {"question": "Veber alьternirlashgan sindromida kaysi BMN zararlanadi?", "answers": ["III", "V", "VII", "XII"], "correct": 0},
    {"question": "Miyyar-Gubler alqternirlashgan sindromida qaysi bmn zararlanadi?", "answers": ["VII", "III", "VIII", "XI"], "correct": 0},
    {"question": "Miya ustuninn nima xosil qiladi", "answers": ["Uzunchok miya, miya kuprigi, miya oyokchasi", "Orka miya, uzunchok miya", "Uzunchok miya, miyacha", "Uzunchok miya, miya kuprigi"], "correct": 0},
    {"question": "Jekson alternirlashgan sindromida kaysi BMN zararlanadi?", "answers": ["XII", "V", "VII", "VIII"], "correct": 0},
    {"question": "Kaysi alternirlashgan sindromda III BMN zararlanadi?", "answers": ["Veber", "Miyar-Gubler", "Fovilь", "Vallenberg-Zaxarchenko"], "correct": 0},
    {"question": "Kaysi alternirlashgan sindromda yuz nervining periferik falajlashi kuzatiladi?", "answers": ["Miyyar-Gubler", "Veber", "Fovilь", "Vallenberg-Zaxarchenko"], "correct": 0},
    {"question": "Veber alternirlashgan sindromida aysi BMN zararlanadi?", "answers": ["III", "V", "VII", "XII"], "correct": 0},
    {"question": "Miyyar-Gubler alьternirlashgan sindromida kaysi bmnzararlanadi?", "answers": ["VII", "III", "VIII", "XI"], "correct": 0},
    {"question": "Ixtiyoriy harakat yo‘li I neyronining vazifasi:", "answers": ["Tormozlovchi, stimullovchi", "Harakatlantiruvchi ta'sir ko‘rsatadi", "Sezuvchi ta'sir ko‘rsatadi", "Gipotonik ta'sir ko‘rsatadi"], "correct": 0},
    {"question": "Kesishmagan piramida yo‘li nima deb ataladi?", "answers": ["Tyurk yo‘li", "Monakov yo‘li", "Govere yo‘li", "Burdax yo‘li"], "correct": 0},
    {"question": "Markaziy falajlikka xos", "answers": ["Muskul gipertoniyasi", "Tishli g‘aldirak” simptomi", "Muskul tonusining plastik tipda oshishi", "Giperkinez"], "correct": 0},
    {"question": "Po‘stlok osti tugunlari qaysi sistemaga kiradi?", "answers": ["Ekstrapiramida", "Piramida", "Koordinatsiya", "To‘g‘ri javob yo‘q"], "correct": 0},
    {"question": "Miyacha yarim sharlarini nima bog‘lab turadi?", "answers": ["Miyacha chuvalchanga", "Tishli yadro", "Dumsimon yadro", "Sharsimon yadro"], "correct": 0},
    {"question": "Miyachada nechta yadro bor?", "answers": ["4 juft", "2 juft", "3 juft", "1 juft"], "correct": 0},
    {"question": "Miyachaning nechta oyoqchasi bor?", "answers": ["3 juft", "2 juft", "4 juft", "1 juft"], "correct": 0},
    {"question": "Nistagm turlarini sanang?", "answers": ["1, 2, 3 to‘g‘ri", "Hammasi to‘g‘ri", "Faqat 1 to‘g‘ri", "Faqat 3 to‘g‘ri"], "correct": 0},
    {"question": "Ixtiyoriy harakat yo‘li I neyronining vazifasi:", "answers": ["Tormozlovchi, stimullovchi", "Harakatlantiruvchi ta'sir ko‘rsatadi", "Sezuvchi ta'sir ko‘rsatadi", "Gipotonik ta'sir ko‘rsatadi"], "correct": 0},
    {"question": "Kesishmagan piramida yo‘li nima deb ataladi?", "answers": ["Turk yo‘li", "Monakov yo‘li", "Govere yo‘li", "Burdax yo‘li"], "correct": 0},
    {"question": "Markaziy falajlikka xos:",    "answers": ["Muskul gipertoniyasi", "Tishli g‘aldirak” simptomi", "Muskul tonusining plastik tipda oshishi", "Giperkinez"],    "correct": 0}
];
