const questions  = [
    {"question": "Yuz nervi nevritida qaysi muskullar zararlanadi?", "answers": ["Mimik muskullar", "Chaynov muskullari", "M.palpebralis superior", "M.sternocleidomastoideus"], "correct": 0},
    {"question": "Bosh miyaning qaysi nervlari zararlanganda bulьbar falajlik kuzatiladi?", "answers": ["IX, X, XII", "IX, X, XI", "VIII, IX, X", "VII, X, XII"], "correct": 0},
    {"question": "Qaysi bosh miya nervi yadrosi bosh miya yarimsharlari po‘stlog‘i bilan bir tomonlama innervatsiyalanadi?", "answers": ["XII, VII", "XII, X", "IX, X", "III, IV, VI"], "correct": 0},
    {"question": "Yutishning buzilishi qaysi muskullar zararlanganini bildiradi?", "answers": ["Yumshoq tanglay muskullari", "Chaynov muskullari", "Mimik muskullar", "Ensa muskullari"], "correct": 0},
    {"question": "N.accesorius kalla suyagidan qaysi teshik orqali chiqadi?", "answers": ["Buyinturuq teshik", "Yumaloq teshik", "Oval teshik", "Til osti kanali"], "correct": 0},
    {"question": "Til chap tomonga kiyshaygan, atrofiya, fibrillyar tortishishlar tilning chap qismida kuzatiladi. O‘ng tomonlama gemiparez. Bemorda qanday sindrom rivojlangan?", "answers": ["Djekson", "Babinskiy - Najot", "Shmidt", "Avelis"], "correct": 0},
    {"question": "Fotopsiya kachon kuzatiladi?", "answers": ["Ensa bulaga qitiqlanganda", "Orqa miyaga qon quyilganda", "VIII nerv nevritida", "Yuz nervi nevritida"], "correct": 0},
    {"question": "Geteronim gemianopsiya kachon kuzatiladi?", "answers": ["Gipofiz o‘smasida", "Orqa miya jaroxatida", "Orqa miya o‘smasida", "Meningitda"], "correct": 0},
    {"question": "Corona radiata zararlanganda nima kuzatiladi?", "answers": ["Gemianopsiya", "Amavroz", "Anosmya", "Agevziya"], "correct": 0},
    {"question": "Xid bilishning yo‘qolishi nima deyiladi?", "answers": ["Anosmiya", "Agevziya", "Anopsiya", "Abuliya"], "correct": 0},
    {"question": "Bemorda bitemporal gemianopsiya kuzatiladi. Zararlangan soxani ko‘rsating.", "answers": ["Xiasma opticus", "Ko‘ruv nervi", "Ko‘ruv trakti", "Corona radiata"], "correct": 0},
    {"question": "Vegetativ nerv sistemasini segment usti qismini kursating.", "answers": ["Limbiko-retikulyar kompleks, gipotalamus", "Tusiq, kuriv dumbog‘i", "Qora substantsiya, qizil yadro", "Orolcha, dumli yadro"], "correct": 0},
    {"question": "Orqa miyada joylashgan parasimpatik xujayralar joyini kursating.", "answers": ["S3-5 - oldingi shox", "L1-5 - oldingi shox", "S1-5 - oldingi shox", "S5-8 –oldingi shox"], "correct": 0},
    {"question": "Trapetsiyasimon mushakda chaqiriladigan vegetativ refleksni kursating.", "answers": ["Pilomotor", "Maxalliy dermografizm", "Reflektor dermografizm", "Pilomotor"], "correct": 0},
    {"question": "Vitseral reflekslarni kursating.", "answers": ["Orto va klinostatik sinama", "Maxalliy va reflektor dermografizm", "Pilomotor refleks", "Qorachiq refleksi"], "correct": 0},
    {"question": "Gipotalamusning zararlanish sindromlarini kursating.", "answers": ["Kardiovaskulyarnыmi, endokrinnыmi narusheniyami", "Argayll-Robertsona Sindrom", "Paroksizmalьnыye narusheniya mыshechnogo tonusa", "Gorner sindromi"], "correct": 0},
    {"question": "Chegara oldi ustuni zaralanish sindromlari.", "answers": ["Xurujsimon og‘riq", "Kardiovaskulyar,endokrin buzilish", "Ter ajralishi, pilomator reflekslarni yuqolishi", "Gorner sindromi"], "correct": 0},
    {"question": "Siliospinal markazni zararlanish sindromini kursating.", "answers": ["Gorner sindromi", "Parodoksal siydik tutolmaslik, impotentsiya", "Ter ajralishi, pilomator reflekslarni yuqolishi", "Truntsitlar, ganglionitlar"], "correct": 0},
    {"question": "Peshona bo‘lagi zararlangandagi patologiyani ko‘rsating.", "answers": ["Agrafiya", "Aleksiya", "Apraksiya", "Agnoziya"], "correct": 0},
    {"question": "Bemor mustakil kiyina olmaydi, tugmalrini qaday olmaydi. Parez va falajliklar yo‘k. Patologiyani ko‘rsating.", "answers": ["Aleksiya", "Apraksiya", "Agnoziya", "Anozognoziya"], "correct": 0},
    {"question": "Bemorda davriy ravishda ko‘zlarini oldida yorin uchunlar, nuktalar paydo bo‘ladi (fotomalar). Ta'sirlanish bosh miyaning kaysi bo‘lagida joylashgan.", "answers": ["Ensa bo‘lagi", "Chakka bo‘lagining ichki yuzasi", "Peshona bo‘lagi", "Tepa bo‘lagi"], "correct": 0},
    {"question": "Po‘stlok markazlari zararlanganda nutkni buzilishi.", "answers": ["Afaziya", "Alaliya", "Dislaliya", "Mutizm"], "correct": 0},
    {"question": "Motor nutkni tekshirishda xarakatlar ketma-ketligi.", "answers": ["Xarf, bo‘gin, so‘zlarni takrorlash.", "Og‘zaki nutk", "Ko‘rsatilgan buyumlar nomini nomlash", "Avtomatik katorli nutk"], "correct": 0},
    {"question": "Bemorda motor afaziya simptomlari bor. Zaralanish uchog‘ini kursating.", "answers": ["44-45 Brodman soxasi.", "22 Vernike soxasi", "37 soxa.", "46 soxa"], "correct": 0},
    {"question": "Bemor uz tana kisimlarini tanimaydi, ung va chap tomonlarini ajratolmaydi, barmoklarini ajratolmaydi. Patologiyani kursating.", "answers": ["Autotoprognoziya.", "Apraksiya", "Aleksiya", "Anozognoziya"], "correct": 0}
];
