const questions = [
    {"question": "Qayer zararlanganda xidlov gallyutsinatsiyalari ko‘zatiladi", "answers": ["Bosh miya chakka qismi", "Xidlov do‘ngalagi", "Xidlov piyozchasi", "Bosh miya tepa qismi"], "correct": 0},
    {"question": "Bitemporal gemianopsiya qayer zararlanganda ko‘zatiladi", "answers": ["Xiazmani markaziy qisimlarini", "Xiazmani tashqi qisimlarini", "Ko‘ruv traktlarini", "Ko‘ruv nurlanishini ikki tomonlama zararlanishida"], "correct": 0},
    {"question": "Yuqoriga ko‘ruv falajligi va qonvergentsiyani buzilishida o‘choq qayerda joylashgan", "answers": ["O‘rta miya tomining dorsal qismida", "Miya ko‘prigini yuqori qismida", "Miya ko‘prigini pastki qismida", "Miya oyoqchalarida"], "correct": 0},
    {"question": "Qayer zararlanganda binazal gemianopsiya ko‘zatiladi", "answers": ["Ko‘ruv nervini kesishmiasini tashki qismlari", "Ko‘ruv nurlanishi", "Ko‘ruv traktlari", "To‘g‘ri javob yo‘q"], "correct": 0},
    {"question": "Qontsentrk ko‘ruv maydonini torayishiga qaysi strukturalarni zararlanishii olib keladi", "answers": ["Ko‘ruv nervin kesishmasi", "Ko‘ruv trakti", "Tashki tizzasimon tancha", "Ko‘ruv nurlanishi"], "correct": 0},
    {"question": "Ko‘ruv traktini zazarlanishida qanday turdagi gemanopsiya vujudga keladi", "answers": ["Gomonim", "Binazal", "Bitemporal", "Pastki kvadrant"], "correct": 0},
    {"question": "Qayer zararlanganda gomonim gemianopsiya uchramaydi", "answers": ["Ko‘ruv nervi kesishmasi", "Ko‘ruv trakti", "Ko‘ruv nurlanishi", "Ichki kasula"], "correct": 0},
    {"question": "Qaysi turdagi ataksiyada Romberg xolatida chaykalish ko‘zni yumgan xolda kuchayadi", "answers": ["Sensitiv", "Miyacha", "Vestibulyar", "Po‘stloq"], "correct": 0},
    {"question": "Miyachani yuqori oyoqchalaridan o‘tadigan yo‘lni ko‘rsating", "answers": ["Oldingi orqa miya-miyacha yo‘li", "Orqa orqa miya-miyacha yo‘li", "Pyoshona-ko‘prik-miyacha yo‘li", "Ensa-chakka-ko‘prik-miyacha yo‘li"], "correct": 0},
    {"question": "Bajaradigan funktsiyasiga ko‘ra IV juft nerv", "answers": ["Harakat nervi", "Sezgi nervi", "Aralash", "Simpatik"], "correct": 0},
    {"question": "Galtaksimon nerv ko‘z olmasini qaysi tomonga buradi", "answers": ["Pastga va tashqariga", "Yuqoriga", "Tashqariga", "Pastga"], "correct": 0},
    {"question": "IV juft kranial nervi qaysi funktsiyani bajaradi", "answers": ["Ko‘zharakatlantiruvchi", "Ko‘ruv", "Xid biluvchi", "Ta'm biluvchi"], "correct": 0},
    {"question": "IV juft kranial nervi zararlanganda qanday buzilishlar yuzaga keladi", "answers": ["Pastga va tashqariga qaraganda diplopiya", "Ptoz", "Midriaz", "Mioz"], "correct": 0},
    {"question": "Bemorni pastga va tashqariga qaraganda ikkita ko‘rish bezovta kiladi. Ob'ektiv: pastga va tashqariga qaraganda harakat cheklanishi ko‘zatiladi. Nima zararlangan", "answers": ["IV juft", "III juft", "VI juft", "II juft"], "correct": 0},
    {"question": "Bemor o‘ngga qaraganda ikkita ko‘rish bezovta kiladi. Ob'ektiv: o‘ng ko‘z olmasining tashqariga harakati cheklanishi ko‘zatiladi. Nima zararlangan", "answers": ["VI juft", "IV juft", "III juft", "II juft"], "correct": 0},
    {"question": "Bemor yuzida o‘ng tomonlama yengil assimetriya, o‘ng yelkasining tushishi ko‘zatiladi. Ob'ektiv: o‘ng tomonlama poluptoz, enoftalьm, mioz. Nima zararlangan", "answers": ["Siliospinal markaz", "IV juft", "III juft", "II juft"], "correct": 0},
    {"question": "Bemorda o‘ng tomonlama yakinlashtiruvchi gilaylik va o‘ngga qaraganda predmetlarning ikkilanishi ko‘zatiladi. Nima zararlangan", "answers": ["VI juft", "IV juft", "III juft", "II juft"], "correct": 0},
    {"question": "VI juft nerv zaralanganda qanday simptomlar yuzaga keladi", "answers": ["Yakinlashtiruvchi gilaylik va yenga qaraganda predmetlarning ikkilanishi", "Ptoz", "Mioz", "Midriaz"], "correct": 0},
    {"question": "IV juft nerv zararlanganda qanday simptomlar ko‘zatiladi", "answers": ["Tashqariga qaraganda diplopiya", "Enoftalьm", "Ptoz", "Midriaz"], "correct": 0},
    {"question": "Bemorda yaqinlashtiruvchi gilaylik, yenga qaraganda diplopiya ko‘zatiladi. Nima zararlangan", "answers": ["VI juft", "IV juft", "III juft", "II juft"], "correct": 0},
    {"question": "Bemorda uzoqlashtiruvchi gilaylik ko‘zatiladi. Nima zararlangan", "answers": ["III juft", "IV juft", "II juft", "VI va IV juftlar"], "correct": 0},
    {"question": "Yuqori kiyshik mushak ko‘z olmasini qaysi tomonga buradi",    "answers": ["Pastga va tashqariga", "Tepaga va ichiga", "Pastka va ichiga", "Tashqariga"],    "correct": 0},
    {"question": "Bemorda yarim ptoz, enoftalьm, mioz ko‘zatiladi. Nima zararlangan", "answers": ["Siliospinal markaz", "VI juft", "IV juft", "II juft"], "correct": 0},
    {"question": "Poluptoz, mioz, enoftalьm bilan kechadigan simptom qanday ataladi", "answers": ["Klod-bernara-gorner sindromi", "Yuqori ko‘z yorigi simptomi", "Argayl-robertsona simdromi", "Bella simptomi"], "correct": 0},
    {"question": "Pastki to‘g‘ri mushak ko‘z olmasini qaysi tomonga buradi", "answers": ["Pastga va ichiga", "Tepaga va tashqariga", "Tashqariga", "Ichiga"], "correct": 0}
];