const questions = [
    {"question": "Qaysi sindromda oral avtomatizm refleksii xarakterli", "answers": ["Soxtabulьbar", "Sharko sindromi", "Bulьbar", "Astenik"], "correct": 0},
    {"question": "Reflektor yoyi nechta qismdan iborat", "answers": ["Afferent", "Efferent", "Afferent va Efferent", "Periferik"], "correct": 1},
    {"question": "Qo‘lda patologik piramida simptomi – refleksi", "answers": ["Rossolimo", "Sheffer", "Oppengeym", "Babinskiy"], "correct": 0},
    {"question": "Nima zararlanganda patologik reflekslar xarakterli", "answers": ["Markaziy harakat neyroni", "Periferik harakat neyroni", "Miyacha", "Talamus"], "correct": 0},
    {"question": "Medullyar qonus zararlanganda qaysi reflekslar pasayadi", "answers": ["Anal", "Axill", "Tovon", "Kremaster"], "correct": 0},
    {"question": "Oyoqni tizza va dumgaza son bo‘gimida bukkanda birdaniga paralich tomonda passiv tovon barmoklarini bukilishi ko‘zatildi. Bu simptom qanday nomlanadi", "answers": ["Mari-fua-bexterev", "Rossolimo", "Bexterev", "Gunn"], "correct": 0},
    {"question": "Bitseps refleksiga orqa miyaning qaysi segmenti javob beradi", "answers": ["S5-S6", "L2-4", "D7-D8", "L5-S1"], "correct": 0},
    {"question": "Tritseps refleksiga orqa miyaning qaysi segmenti javob beradi", "answers": ["S7-S8", "D7-D8", "L2-4", "S5-S6"], "correct": 0},
    {"question": "Patellyar refleksiga orqa miyaning qaysi segmenti javob beradi", "answers": ["L2-4", "S5-S6", "S7-S8", "D7-D8"], "correct": 0},
    {"question": "Axillov refleksiga orqa miyaning qaysi segmenti javob beradi", "answers": ["L5-S1", "D7-D8", "L2-4", "S5-S6"], "correct": 0},
    {"question": "Yuqori qorin refleksiga orqa miyaning qaysi segmenti javob beradi", "answers": ["D7-D8", "S7-S8", "S5-S6", "L5-S1"], "correct": 0},
    {"question": "O‘rta qorin refleksiga orqa miyaning qaysi segmenti javob beradi", "answers": ["D9-D10", "S7-S8", "S5-S6", "D7-D8"], "correct": 0},
    {"question": "Medullyar qonus zararlanganda qaysi refleks yo‘qoladi", "answers": ["Anal", "Axill", "Tizza", "Kremaster"], "correct": 0},
    {"question": "Pay va periostal reflekslar qachon oshadi", "answers": ["Markaziy paralichda", "Periferik paralichda", "Periferik va markaziy paralichda", "Orqa miyaning oldingi shoxi zararlanganda"], "correct": 0},
    {"question": "Yozuvchi patologik reflekslarga kirmaydi", "answers": ["Rossolimo", "Sheffer", "Gordon", "Oppengeym"], "correct": 0},
    {"question": "Bukuvchi patologik reflekslarga kirmaydi", "answers": ["Babinskiy", "Bexterev-Mendel", "Jukovskiy", "Jukovskiy"], "correct": 0},
    {"question": "Pay va periostal reflekslar qachon pasayadi", "answers": ["Periferik paralichda", "Periferik va markaziy paralichda", "Orqa miyaning oldingi shoxi zararlanganda", "Markaziy paralichda"], "correct": 0},
    {"question": "Patologik reflekslar nima zararlanganda xarakterli", "answers": ["Markaziy harakat neyroni", "Miyacha", "Talamus", "Ichki kapsula"], "correct": 0},
    {"question": "Markaziy harakat neyroni zararlanganda chuqur reflekslar", "answers": ["Oshadi", "O‘zgarmaydi", "Biroz oshadi", "Pasayadi"], "correct": 0},
    {"question": "Periferik harakat neyroni zararlanganda chuqur reflekslar", "answers": ["Pasayadi", "Biroz oshadi", "Oshadi", "O‘zgarmaydi"], "correct": 0},
    {"question": "Yanishevskiy refleksi qaysi qism zararlanganda ko‘zatiladi", "answers": ["Pyoshona qism", "Chakka qism", "Tepa qism", "Ensa qism"], "correct": 0},
    {"question": "Markaziy neyron zararlanganda chuqur sezgi", "answers": ["Oshadi", "O‘zgarmaydi", "Pasayadi", "O‘zgaradi"], "correct": 0},
    {"question": "Periferik neyron zararlanganda chuqur sezgi", "answers": ["Pasayadi", "Oshadi", "O‘zgarmaydi", "O‘zgaradi"], "correct": 0},
    {"question": "Qanday analizatorlar bor, ortiqchasini chiqaring", "answers": ["Nerv", "Ko‘ruv", "Eshituv", "Xidlov"], "correct": 0},
    {"question": "Ichki ta'sirlanish natijasida yuzaga keladigan sezgi nima deb ataladi", "answers": ["Interotseptiv", "Ichki", "Yuza", "Eksterotseptiv"], "correct": 0}
];